"""Configuration package for the CSD Analyzer application."""

from .visualization_config import (
    BLUES_PALETTE, AQUA_PALETTE, PURPLE_PALETTE,
    VOLUME_PALETTE, PRIORITY_PALETTE, CSAT_PALETTE, HEATMAP_PALETTE,
    ROOT_CAUSE_PALETTE, PLOT_STYLE, FIGURE_DPI,
    DEFAULT_FIGURE_SIZE, WIDE_FIGURE_SIZE, SQUARE_FIGURE_SIZE,
    FONT_FAMILY, TITLE_FONT_SIZE, LABEL_FONT_SIZE,
    TICK_FONT_SIZE, LEGEND_FONT_SIZE,
    GRID_STYLE, LEGEND_STYLE, AXIS_STYLE,
    TIME_SERIES_SETTINGS, BAR_PLOT_SETTINGS,
    BOX_PLOT_SETTINGS, HEATMAP_SETTINGS,
    DISTRIBUTION_SETTINGS, EXPORT_SETTINGS,
    ANIMATION_SETTINGS, LIGHT_THEME, DARK_THEME
)

from .api_config import (
    OPENAI_SETTINGS, SALESFORCE_SETTINGS,
    API_ENDPOINTS, QUERY_TEMPLATES,
    ERROR_MESSAGES, RATE_LIMITS,
    RETRY_SETTINGS, get_auth_settings,
    CACHE_SETTINGS, LOGGING_SETTINGS,
    TIMEOUT_SETTINGS
)

__all__ = [
    # Visualization settings
    'BLUES_PALETTE', 'AQUA_PALETTE', 'PURPLE_PALETTE',
    'VOLUME_PALETTE', 'PRIORITY_PALETTE', 'CSAT_PALETTE',
    'HEATMAP_PALETTE', 'ROOT_CAUSE_PALETTE',
    'PLOT_STYLE', 'FIGURE_DPI',
    'DEFAULT_FIGURE_SIZE', 'WIDE_FIGURE_SIZE', 'SQUARE_FIGURE_SIZE',
    'FONT_FAMILY', 'TITLE_FONT_SIZE', 'LABEL_FONT_SIZE',
    'TICK_FONT_SIZE', 'LEGEND_FONT_SIZE',
    'GRID_STYLE', 'LEGEND_STYLE', 'AXIS_STYLE',
    'TIME_SERIES_SETTINGS', 'BAR_PLOT_SETTINGS',
    'BOX_PLOT_SETTINGS', 'HEATMAP_SETTINGS',
    'DISTRIBUTION_SETTINGS', 'EXPORT_SETTINGS',
    'ANIMATION_SETTINGS', 'LIGHT_THEME', 'DARK_THEME',
    
    # API settings
    'OPENAI_SETTINGS', 'SALESFORCE_SETTINGS',
    'API_ENDPOINTS', 'QUERY_TEMPLATES',
    'ERROR_MESSAGES', 'RATE_LIMITS',
    'RETRY_SETTINGS', 'get_auth_settings',
    'CACHE_SETTINGS', 'LOGGING_SETTINGS',
    'TIMEOUT_SETTINGS'
] 