# Salesforce Credentials
SF_USERNAME = "case.analytics.integration@eightfold.ai"
SF_PASSWORD = "C@s3@nalyt1cs@135$$"
SF_SECURITY_TOKEN = "YkXvFzkDp6YnAQs7PZWju3eCv"
SF_DOMAIN = "login"  # Optional, defaults to 'login' 

# OpenAI API Key
OPENAI_API_KEY = "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" 