# Salesforce Credentials
SF_USERNAME = "case.analytics.integration@eightfold.ai"
SF_PASSWORD = "C@s3@nalyt1cs@135$$"
SF_SECURITY_TOKEN = "YkXvFzkDp6YnAQs7PZWju3eCv"
SF_DOMAIN = "login"  # Optional, defaults to 'login' 